# Generated by Django 4.1.7 on 2023-03-27 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_item_purchase', models.CharField(blank=True, max_length=255, null=True)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('purchase_limit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('favorite_category', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
