# Generated by Django 4.1.7 on 2023-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_pricealert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
