# Generated by Django 4.1.7 on 2023-03-28 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_userprofile_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='whatsapp_number',
        ),
    ]
