# Generated by Django 4.1.7 on 2023-03-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_remove_userprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
